### ISSUE TITLE
iOS 9

### ISSUE THREAD

**Issue by mrsnax** [dingwilson/SwiftVideoBackground#10]
can this pod use for iOS 9 ?

**Comment by dingwilson** [comment]
Hi @mrsnax 

I have modified the minimum deployment target to accept iOS 8.0 and later for the latest release (1.0.1). Please update to the latest version and see if that fixes your issue.

Thanks for trying SwiftVideoBackground! 👍 

Wilson

**Comment by mrsnax** [comment]
thank you for the updated ! love it !
