### ISSUE TITLE
Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by mrsnax** [dingwilson/SwiftVideoBackground#11]
Hi

I tried the VideoBackground when running project facing a error like this ?

`Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value`

And the code like this :

`backgroundVideo.createBackgroundVideo(name: "Video", type: "mp4")`
`backgroundVideo.isMuted = true` 

FYI, I've done to embedded the video and copy if Need to the proejcts

any suggestion ?

**Comment by dingwilson** [comment]
Hmm, I cannot seem to replicate this issue. Do you happen to know what optional is producing the nil?

**Comment by mrsnax** [comment]
Hi wilson

Its my fault, the video only work for UIView not UIViewController 😋 

Chase Close 👍
