### ISSUE TITLE
Video not fit

### ISSUE THREAD

**Issue by mrsnax** [dingwilson/SwiftVideoBackground#12]
Hi,

I using constraint with all safe area, but my video doesn't fit to full when Im changing iPhone X to iPhone 8 simulator.

How to fix this?

**Comment by dingwilson** [comment]
I have not had a chance to test iPhone X safe area constraints. If possible, could you show me via screenshots what you mean? I will take a look at it when I have a chance. Thanks!

**Comment by mrsnax** [comment]
Here's the screenshots

![img_d933e18f1bd6-1](https://user-images.githubusercontent.com/6369589/32976985-4e3d1d1e-cc56-11e7-95b8-43d2adb9c88c.jpeg)

its iPhone 8 Plus, when changing into iPad, the video only fit 30% of screens

**Comment by dingwilson** [comment]
Ahh, I see. Are you using auto-layout? I believe this issue is similar to #1 . Please see my response to that issue (quoted below):

> I have also run into this issue with a different project of mine (not related to SwiftVideoBackground) when using AutoLayout on a UIView (or UIView-based objects such as UIImageView). I don't think that the issue is with the background video, as it will fill the dimensions of the UIView. Rather, I think that autolayout is incorrectly setting the wrong constraints for the UIView, according to the size class selection you used (in your case, iPhone 4s). This seems to be due to the new size class options (and removal of Any,Any) in the interface builder in Xcode 8+.
>
> A temporary solution is to select the proper phone version in the storyboard, as shown in the image you posted, and then building/running for that phone. (iPhone 4s -> iPhone 4s, or iPhone 7 -> iPhone 7).

See if that fixes your issue for you.

**Comment by mrsnax** [comment]
Yep its autolayout but when im Archive the projects the conflicts still not resolve. 

Any solution else?

**Comment by dingwilson** [comment]
Hmm, in that case, I'm not sure what the issue might be. Do you have this issue with other UI elements? (ex: Can you create a random UIView with the same constraints and see if you have the same auto layout issues?)

**Comment by dingwilson** [comment]
I hope that you managed to solve your issues! If not, please feel free to reopen or create a new issue. Thanks!
