### ISSUE TITLE
thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

### ISSUE THREAD

**Issue by zaccadams** [dingwilson/SwiftVideoBackground#2]
The following error:
thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

as it highlights:
player = AVPlayer(url: URL(fileURLWithPath: path!))

in the BackgroundView.swift - Using CocoaPods

**Comment by dingwilson** [comment]
Hi @zdog01 ! Thanks for giving SwiftVideoBackground a try 👍 . Can you provide me with the entire stack trace and any other debug information?

Without the extra information, I can only make guesses. This issue looks like the BackgroundVideo object cannot find the video, based on the values you pass in for "name" and "type". Did you make sure to target your project when you added the video to your xcworkspace?
