### ISSUE TITLE
Use of unresolved identifier 'VideoBackground()'?

### ISSUE THREAD

**Issue by csr** [dingwilson/SwiftVideoBackground#21]
Was this library recently updated?

    import UIKit
    import SwiftVideoBackground

    class MyViewController: UIViewController {
        private let videoBackground = VideoBackground() // error
    }

is no longer working: `Use of unresolved identifier 'VideoBackground'`.

**Comment by quanvo87** [comment]
The above code should work. Did this happen after a `pod install`? Does cleaning your build folder and re-building do anything? (in Xcode, Product > Clean Build Folder)

**Comment by csr** [comment]
Yeah, thanks for the fast reply. I had out-to-date source repos so I had to run `pod install --repo-update`. Thanks again, closing this.
