### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by csr** [dingwilson/SwiftVideoBackground#25]
So here’s the thing. When I’m playing music and I open the app with this video layer the music stops playing music even though the isMuted property is set to true. Can we make it so that if the video layer is muted this won’t happen? It’s a matter of better UX.

**Comment by csr** [comment]
I can help with this. If would like me to help out I can totally look into it.

**Comment by quanvo87** [comment]
There is a section in the README that should address this: https://github.com/dingwilson/SwiftVideoBackground#preventing-video-from-muting-other-audio-on-device
Let me know you run into any problems.

**Comment by csr** [comment]
It works great! Apologies for not looking into this in the read me in advance. Thanks!

**Comment by quanvo87** [comment]
No prob! The docs should probably be more clear.
