### ISSUE TITLE
Issue with rotation

### ISSUE THREAD

**Issue by csr** [dingwilson/SwiftVideoBackground#26]
If I rotate my iPad the video doesn't adapt to the screen size (please check GIF: https://giphy.com/gifs/l4pSVnVwldE37HkuQ). Is there any way I can fix this?

**Comment by dingwilson** [comment]
Hmm thats interesting... Lets try debugging this and seeing if this is a SwiftVideoBackground issue or a layout issue.

Could you try setting the background color of the view you are using (the one being passed in to SwiftVideoBackground) to something other than clear? Then try running the app again, rotating the iPad horizontally, and see if the color (view) shows full screen.

**Comment by csr** [comment]
Thanks, I think it's the same as before, just the background color changed. Please check out this screenshot:

![simulator screen shot - ipad pro 12 9-inch - 2018-02-13 at 20 34 45](https://user-images.githubusercontent.com/10504710/36187906-53f09740-10fd-11e8-98a9-20d352d6e1b5.png)

**Comment by dingwilson** [comment]
Ok, in that case, it shouldn't be a layout issue. I will look into this and see what I can find. Thanks for letting us know about this issue!

**Comment by quanvo87** [comment]
Ahh...seems like we'll need to hold a weak reference to `UIView` being passed in, and observe for a change in it's frame, and then rebuild the `AVPlayer` accordingly. Maybe there's even a native notification that can tell us when the phone orientation has changed. My first guess at an implementation for a fix.

**Comment by quanvo87** [comment]
I will try to do some work on this tomorrow.

**Comment by dingwilson** [comment]
Hey @cesaredecal 

Just wanted to give you an update! @quanvo87 did some amazing work on the observers to handle device orientation change in PR #30 . This has now been merged into SwiftVideoBackground version 2.0.3, and should fix the issue you described above.

Feel free to update to the latest version and test it out for yourself!

run `pod update SwiftVideoBackground` or modify the entry in your Podfile:

```ruby
pod 'SwiftVideoBackground', '~> 2.0.3'
```

(Note: you might have to update your pod spec repo)

Please let us know if this update works/fixes the bug for you, and thanks again for bringing this issue to our attention! 👍

**Comment by csr** [comment]
Thanks so much guys! will test the new version out very soon.

**Comment by csr** [comment]
Hey guys, I've tried out the new version. It works well but the alpha change isn't applied to the entire screen after rotating the device. Please check this out:

![simulator screen shot - ipad pro 12 9-inch - 2018-02-16 at 10 35 32](https://user-images.githubusercontent.com/10504710/36323338-6b6245fe-1305-11e8-8ca2-0cbecde646ac.png)

**Comment by dingwilson** [comment]
@cesaredecal ahh good catch! I'll get that fixed right away...

**Comment by dingwilson** [comment]
Hey @cesaredecal 

Release 2.0.4 should fix the alpha overlay issues you were dealing with! Sorry about that haha.

Please let us know if you experience any more issues. Thanks again for reporting this issue to us! 👍 

-- Wilson

**Comment by csr** [comment]
thanks Wilson, working great :)
