### ISSUE TITLE
Changing video.

### ISSUE THREAD

**Issue by gilosborne** [dingwilson/SwiftVideoBackground#3]
Hello, I'm trying to use this for onboarding videos. As the user hits next I would like to change the video using the same view. Anyway to do this with this plugin? It currently just stays the same video even though I'm trying to update it when the user hits next.

Thanks!

**Comment by dingwilson** [comment]
@gilosborne I personally have not tried this, but try calling the function `createBackgroundVideo()` again with the name of the new video when the user hits next. Please give that a try and let me know if it works!

If that does not work, I can add some code to provide the ability to de-init the current backgroundVideo AVPlayer, allowing it to be re-init with a new link. 👍

**Comment by gilosborne** [comment]
Let me take a look tomorrow but I do believe I tried that. I'll confirm and let you know. Thanks for the response!:)

Gilbert Osborne

Osborne.xyz

On Thu, Feb 16, 2017 at 5:50 PM Wilson Ding

<
mailto:Wilson Ding <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/gilosborne
I personally have not tried this, but try calling the function

createBackgroundVideo()

again with the name of the new video when the user hits next. Please give that a try and let me know if it works!

If that does not work, I can add some code to provide the ability to de-init the current backgroundVideo AVPlayer, allowing it to be re-init with a new link.

👍

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/dingwilson/SwiftVideoBackground/issues/3#issuecomment-280489006
, or

**Comment by gilosborne** [comment]
Yes, that is what I’m doing. So this is what I have. I can see by printing the index that the value is changing every time I move within the onboarding. I also know that is working because that is the value I’m using to change the copy below the image. But the video isn’t changing out. :/

If I’m missing something please let me know. Also, huge thanks for the help! This library is saving me a lot of time to begin with. :)

print

(

index

)

//Videos

if

(

index

==

0

){

//breeds

onboardingVideo

.

createBackgroundVideo

(

name

:

"HP-onboarding-breeds"

,

type

:

"mp4"

)

}

else

if

(

index

==

1

)

{

//set goal

onboardingVideo

.

createBackgroundVideo

(

name

:

"HP-onboarding-goal"

,

type

:

"mp4"

)

}

else

if

(

index

==

2

)

{

//calendar

onboardingVideo

.

createBackgroundVideo

(

name

:

"HP-onboarding-calendar"

,

type

:

"mp4"

)

}

else

if

(

index

==

3

)

{

//notifications

onboardingVideo

.

createBackgroundVideo

(

name

:

"HP-onboarding-notifications"

,

type

:

"mp4"

)

//phoneGif.image = #imageLiteral(resourceName: "test")

}

else

{

//notifications

onboardingVideo

.

createBackgroundVideo

(

name

:

"HP-onboarding-notifications"

,

type

:

"mp4"

)

}

Gilbert Osborne

Osborne.xyz

On Thu, Feb 16, 2017 at 11:34 PM Gilbert Osborne

<
mailto:Gilbert Osborne <gilbert.osborne@gmail.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Let me take a look tomorrow but I do believe I tried that. I'll confirm and let you know. Thanks for the response!:)

Gilbert Osborne

Osborne.xyz

On Thu, Feb 16, 2017 at 5:50 PM Wilson Ding

<
mailto:Wilson Ding <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/gilosborne
I personally have not tried this, but try calling the function

createBackgroundVideo()

again with the name of the new video when the user hits next. Please give that a try and let me know if it works!

If that does not work, I can add some code to provide the ability to de-init the current backgroundVideo AVPlayer, allowing it to be re-init with a new link.

👍

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/dingwilson/SwiftVideoBackground/issues/3#issuecomment-280489006
, or

**Comment by dingwilson** [comment]
Ok, so I've finally had a chance to sit down and take a look at the code. I have managed to replicate your issue, and I have confirmed that my earlier advice does not seem to not work. I did some research and found that the issue is the way that the AVPlayer (the low level video player I am using) is not really built to be overwritten in the way that I was suggesting.

There is a way to get around this by using `AVPlayerItem` to play the video, and replacing the `AVPlayerItem` to switch the file URL that it is reading from. However, this will probably take me several hours to rewrite/test/deploy the changes, and I won't really have time in the upcoming ~2 weeks or so to do this.

In the meantime, I suggest looking through my main source code [here](https://github.com/dingwilson/SwiftVideoBackground/blob/master/SwiftVideoBackground/BackgroundVideo.swift), as well as [this link](http://stackoverflow.com/questions/35004984/play-video-from-new-url-without-creating-a-new-avplayer-object) to convert the AVPlayer to AVPlayerItem on your own. (If you manage to make it work, please feel free to send a pull request with the changes. 👍) Another possible alternative is to split your app's on-boarding screens/flow into multiple ViewControllers, each with their own SwiftVideoBackground instance.

**Comment by gilosborne** [comment]
No worries, thanks for digging into that! I’ll take a look at what you sent and figure it out. 

Thanks again! Have a great weekend.

Gilbert Osborne

Osborne.xyz

On Fri, Feb 17, 2017 at 1:28 PM Wilson Ding

<
mailto:Wilson Ding <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Ok, so I've finally had a chance to sit down and take a look at the code. I have managed to replicate your issue, and I have confirmed that my earlier advice does not seem to not work. I did some research and found that the issue is the way that the AVPlayer (the low level video player I am using) is not really built to be overwritten in the way that I was suggesting.

There is a way to get around this by using

AVPlayerItem

to play the video, and replacing the

AVPlayerItem

to switch the file URL that it is reading from. However, this will probably take me several hours to rewrite/test/deploy the changes, and I won't really have time in the upcoming ~2 weeks or so to do this.

In the meantime, I suggest looking through my main source code
https://github.com/dingwilson/SwiftVideoBackground/blob/master/SwiftVideoBackground/BackgroundVideo.swift
, as well as
http://stackoverflow.com/questions/35004984/play-video-from-new-url-without-creating-a-new-avplayer-object
to convert the AVPlayer to AVPlayerItem. Another possible alternative is to split your app's on-boarding screens/flow into multiple ViewControllers, each with their own SwiftVideoBackground instance.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/dingwilson/SwiftVideoBackground/issues/3#issuecomment-280728849
, or

**Comment by gilosborne** [comment]
Thought I would let you know what I ended up doing to get around this. I’m just removing all subviews of type Background video then adding the sub view again depending on the variable. Great library, thanks!

//remove all subviews

        for v in view.subviews{

            if v is BackgroundVideo{

                v.removeFromSuperview()

            }

        }

        

        //add BackgroundVideo subview

        let screenWidth = screenSize.width

        let xPosition:CGFloat = (screenWidth-videoWidth)/4

        let testFrame : CGRect = CGRect(x: xPosition, y: yPosition, width: videoWidth, height: videoHeight)

        let videoView:BackgroundVideo = BackgroundVideo(frame: testFrame)

        self.view.addSubview(videoView)

        

        //Videos

        if (index == 0){

            

            //breeds

            videoView.createBackgroundVideo(name: "HP-onboarding-breeds", type: "mp4")

            

        }else if(index == 1) {

            

            //set goal

            videoView.createBackgroundVideo(name: "HP-onboarding-goal", type: "mp4")

        }else if(index == 2) {

            

            //calendar

            videoView.createBackgroundVideo(name: "HP-onboarding-calendar", type: "mp4")

        }else if(index == 3) {

            

            //notifications

            videoView.createBackgroundVideo(name: "HP-onboarding-notifications", type: "mp4")

        }

Gilbert Osborne

Osborne.xyz

On Fri, Feb 17, 2017 at 2:06 PM Gilbert Osborne

<
mailto:Gilbert Osborne <gilbert.osborne@gmail.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

No worries, thanks for digging into that! I’ll take a look at what you sent and figure it out. 

Thanks again! Have a great weekend.

Gilbert Osborne

Osborne.xyz

On Fri, Feb 17, 2017 at 1:28 PM Wilson Ding

<
mailto:Wilson Ding <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Ok, so I've finally had a chance to sit down and take a look at the code. I have managed to replicate your issue, and I have confirmed that my earlier advice does not seem to not work. I did some research and found that the issue is the way that the AVPlayer (the low level video player I am using) is not really built to be overwritten in the way that I was suggesting.

There is a way to get around this by using

AVPlayerItem

to play the video, and replacing the

AVPlayerItem

to switch the file URL that it is reading from. However, this will probably take me several hours to rewrite/test/deploy the changes, and I won't really have time in the upcoming ~2 weeks or so to do this.

In the meantime, I suggest looking through my main source code
https://github.com/dingwilson/SwiftVideoBackground/blob/master/SwiftVideoBackground/BackgroundVideo.swift
, as well as
http://stackoverflow.com/questions/35004984/play-video-from-new-url-without-creating-a-new-avplayer-object
to convert the AVPlayer to AVPlayerItem. Another possible alternative is to split your app's on-boarding screens/flow into multiple ViewControllers, each with their own SwiftVideoBackground instance.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/dingwilson/SwiftVideoBackground/issues/3#issuecomment-280728849
, or

**Comment by dingwilson** [comment]
Ahh yes that's great! I'm glad you managed to get it working in the end! :) Thanks for using SwiftVideoBackground. 👍
