### ISSUE TITLE
Set AVAudioSession to ambient by default?

### ISSUE THREAD

**Issue by quanvo87** [dingwilson/SwiftVideoBackground#32]
The thing that makes the video not mute other sounds playing on the device.

Could set it by default on init, with optional opt out.

**Comment by dingwilson** [comment]
This sounds like a great idea! Do you see this potentially having any negative effect on apps using AVAudioSession for other purposes?

**Comment by quanvo87** [comment]
This will negatively affect them if:
- they purposely want their app to mute other device sounds `&&`
- they init a `VideoBackground` instance with the default params

To avoid this maybe we can:
- clearly put in README what default param does
- make it a required param

Maybe it would be best to make it a required param with no default value.

**Comment by dingwilson** [comment]
ok, personally I think that we should definitely set AVAudioSession to ambient by default. I believe most people wouldn't want to affect existing music/sound unless they have their own music/sound playing (`isMuted = false`).

I think the way we should proceed is this:
- set AVAudioSession to ambient by default
- clearly document this default, what it does, and offer them some easy way (a param maybe?) of changing it.

I think we should try to have as few required params as possible. The fewer params required to get up and running, the better.

What do you think?

**Comment by quanvo87** [comment]
Yea we can do that
