### ISSUE TITLE
Explore implementing conventional commits and automating CHANGELOG

### ISSUE THREAD

**Issue by dingwilson** [dingwilson/SwiftVideoBackground#34]
Implementing [conventional commits](https://conventionalcommits.org) could help add some automation for updating CHANGELOG/releases.

- [ ] Use [semantic-release](https://github.com/semantic-release/semantic-release) with Travis CI
- [ ] Add checks to ensure all commits follow conventional commits

**Comment by quanvo87** [comment]
yea I was trying to follow this. does just the PR name have to follow it? or the first commit of the PR? or every commit...I guess we can just squash all PRs

**Comment by dingwilson** [comment]
either every commit has to follow, or we can squash and just have the PR name follow it. There is also a check for PRs which can prevent merges if commits don't meet the requirements for conventional commits.

**Comment by dingwilson** [comment]
Closing for now - if there is interest, I can reopen later on.
