### ISSUE TITLE
README images not showing up properly in jazzy docs/cocoapods page

### ISSUE THREAD

**Issue by dingwilson** [dingwilson/SwiftVideoBackground#36]
Issue resides in using relative links for all images in Assets folder.

Currently bypassing jazzy docs issue with an extra copy phase in Makefile. Cocoapods images are broken.

We should switch to using absolute references to images.

**Comment by quanvo87** [comment]
what about the raw data link like https://raw.githubusercontent.com/quanvo87/WQNetworkActivityIndicator/master/WQNetworkActivityIndicator/Assets/screenshot.png or is that what you're talking about

**Comment by dingwilson** [comment]
yup! thats exactly what I was talking about. I was originally just calling `Assets/screenshot.png`. I switched everything in the PR to use the raw data link like you listed above.
