### ISSUE TITLE
ability to pass in array of video names and have them played one after another

### ISSUE THREAD

**Issue by quanvo87** [dingwilson/SwiftVideoBackground#40]

**Comment by dingwilson** [comment]
This is a great idea! We should definitely include this as functionality in 3.0.0.

PS: if you need this functionality rn, one hack-y way I've used before is using `ffmpeg` to directly concatenate multiple mp4's into a single file. Here is my [commit](https://github.com/dingwilson/dotfiles/commit/572680e17f7f805d0c80239b062d60faa58a8a4b) on how I did this.
