### ISSUE TITLE
"Unknown class BackgroundVideo in Interface Builder file."

### ISSUE THREAD

**Issue by AudienceofOne1991** [dingwilson/SwiftVideoBackground#5]
Getting this runtime error. In your example project, when run 'pod install', it works, but gives this warning:

[!] The `ExampleLogin [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-ExampleLogin/Pods-ExampleLogin.release.xcconfig'. This can lead to problems with the CocoaPods installation

**Comment by dingwilson** [comment]
Hey @AudienceofOne1991 ! 

Thanks for trying SwiftVideoBackground. 👍

For your runtime error, check to see whether you have the proper settings in your storyboard. Click on the UIView object you created for BackgroundVideo, and then see if it matches the following screenshot:

![Screenshot](https://cloud.githubusercontent.com/assets/8827679/24661736/ca6232cc-1918-11e7-9ba9-8ed953401cce.jpeg)

In terms of the warning, it is misconfiguration of some of the build settings in my example. Thanks for showing me! It shouldn't really affect the overall functionality of SwiftVideoBackground, but I'll see if I can fix it.

Please let me know if you have any other issues. Thanks!

Regards
Wilson Ding

**Comment by AudienceofOne1991** [comment]
ah, ok. connecting the module in the storyboard fixed it! and thank you, it's a great pod!

**Comment by dingwilson** [comment]
I'm glad it helped! :) Thanks for using SwiftVideoBackground. 👍
