### ISSUE TITLE
Deprecate Multiple Videos in Single View

### ISSUE THREAD

**Issue by dingwilson** [dingwilson/SwiftVideoBackground#52]
Deprecate ability to play multiple videos one-after-another in the same view, due to issues with how Apple handles each video. This feature will be removed in release 3.0.0.

- [ ] Add deprecation message for next patch release
- [ ] Remove feature in release 3.0.0
- [ ] Add alternative solution using FFMPEG to concatenate video assets

**Comment by quanvo87** [comment]
For reference this is a rough cut of the code that worked for me for merging vids (sound removed):
```swift
func merge(arrayVideos: [AVAsset], completion: @escaping (AVAssetExportSession) -> ()) -> Void {
        let mainComposition = AVMutableComposition()
        let compositionVideoTrack = mainComposition.addMutableTrack(withMediaType: .video, preferredTrackID: kCMPersistentTrackID_Invalid)

        var insertTime = kCMTimeZero

        for videoAsset in arrayVideos {
            try! compositionVideoTrack?.insertTimeRange(CMTimeRangeMake(kCMTimeZero, videoAsset.duration), of: videoAsset.tracks(withMediaType: .video)[0], at: insertTime)
            insertTime = CMTimeAdd(insertTime, videoAsset.duration)
        }

        let outputFileURL = URL(fileURLWithPath: NSTemporaryDirectory() + "merge.mp4")

        let fileManager = FileManager()
        try? fileManager.removeItem(at: outputFileURL)

        let exporter = AVAssetExportSession(asset: mainComposition, presetName: AVAssetExportPresetHighestQuality)

        exporter?.outputURL = outputFileURL
        exporter?.outputFileType = AVFileType.mp4
        exporter?.shouldOptimizeForNetworkUse = true

        exporter?.exportAsynchronously {
            DispatchQueue.main.async {
                completion(exporter!)
            }
        }
    }
```

**Comment by quanvo87** [comment]
Maybe we can keep it in...there are uses for it, like when you only know what videos you want to play at runtime.

That said it should really only be promoted if we:
- make a vid merging lib
- pull in that lib as a dependency and merge vids, then play
- warn that there is some async processing time involved, that grows with the video sizes
  - this processing time is not that bad from my experience
  - a loading indicator/thumbnail could be showed if desired
  - it's better than having a delay between each vid

But yes we should def encourage using something like FFMPEG to pre-merge your vid wherever possible (such as a static app welcome screen vid, which is prob mostly what this lib is used for)
