### ISSUE TITLE
Migrate to singleton

### ISSUE THREAD

**Issue by dingwilson** [dingwilson/SwiftVideoBackground#53]
Only one instance of VideoBackground is needed to display any number of video backgrounds on views. Therefore, we will be migrating to a singleton. Note that this will be a breaking change, and will probably occur at release 3.0.0

**Comment by quanvo87** [comment]
There is already a singleton option, and I guess we could leave init public and deprecate it.

**Comment by dingwilson** [comment]
@quanvo87 this will no longer be necessary after our decision to switch to a UIView extension moving forward, correct?

**Comment by quanvo87** [comment]
Correct

**Comment by dingwilson** [comment]
Oops, just read your message in the PR.. I'll leave this open until we decide how we want to move forward.
