### ISSUE TITLE
fix broken images on CocoaPods page, add screen shot

### ISSUE THREAD

**Issue by quanvo87** [dingwilson/SwiftVideoBackground#59]
https://cocoapods.org/pods/SwiftVideoBackground

You can add a screen shot from the Podspec. It will display on the right side bar on the CocoaPods page. I believe this can also be a gif, in which the screenshot could be the Spotify thing.

a reference: https://cocoapods.org/pods/GMStepper

**Comment by dingwilson** [comment]
whoa thats pretty cool! I'll add the Screenshot to the podspec.

The broken images on CocoaPods page was fixed a while ago. However, CocoaDocs (the service being used to regen the docs) has been down for a few weeks now. Waiting for it to go back up before I can trigger a re-parse. See: https://github.com/CocoaPods/cocoadocs.org/issues/585
