### ISSUE TITLE
mute the video 

### ISSUE THREAD

**Issue by AbdulazizAlmohsen** [dingwilson/SwiftVideoBackground#6]
is there anyway to mute the video ?

**Comment by dingwilson** [comment]
There is currently no functionality built in to control the volume of the video being played. That is definitely a feature that should be included, and I will push out an update in the near future with volume control functionality.

**Comment by dingwilson** [comment]
@AbdulazizAlmohsen 

I have created SwiftVideoBackground version 0.07, which includes a boolean `isMuted`.

```swift
backgroundVideo.isMuted = true
```

Setting isMuted to true will cause the background video to be muted.

Thanks for trying SwiftVideoBackground, and I hope this update helps solve your issue! 👍
