### ISSUE TITLE
Crash on cleanUp

### ISSUE THREAD

**Issue by ndemie** [dingwilson/SwiftVideoBackground#64]
https://github.com/dingwilson/SwiftVideoBackground/blob/78cbe752332dfa3766a899ff794fbd567e355b5c/SwiftVideoBackground/Sources/VideoBackground.swift#L181

Crashes on above line due to the superview of that view being nil sometimes

**Comment by quanvo87** [comment]
Thanks for the catch. We should have a fix out by today.

**Comment by ndemie** [comment]
Actually, after testing the issue seems to be something else. I haven't found the cause yet, but even after adding a check it can fail

**Comment by quanvo87** [comment]
I see. Yes, I thought it was safe to call `removeFromSuperview` without checking for nil, though [Apple docs](https://developer.apple.com/documentation/uikit/uiview/1622421-removefromsuperview) aren't 100% clear. Is it possible to post the other code you're using to get the occasional crash? In the meantime I'll do my own investigation.

**Comment by ndemie** [comment]
It's basically just this. And it fails when going back to this viewcontroller on the earlier mentioned line. Earlier versions of the library did not have this problem.

```
private let videoBackground = VideoBackground()

override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        try? videoBackground.play(view: backgroundImage, videoName: "swapOnboarding", videoType: "mp4")
}
```

**Comment by ndemie** [comment]
Actually, some more digging has taken me to the issue.

Before the play is called on the `videoBackground`, `view.layoutIfNeeded()` is called. If I comment that bit, the library will not crash the app. The crash does not happen on an iPhone X, but it does happen on a 6S. Both running 11.2.5

**Comment by quanvo87** [comment]
I wasn't able to recreate the crash. I think there may be many other relevant factors. I'll keep looking into possible consequences of these interactions.

One question I have: do you need to play the vid in `viewWillAppear`? Having the vid play on `viewDidLoad` or `init` should be fine. Having it replay in `viewWillAppear` restarts the vid from the  beginning every time the view controller re-appears. If that's your intended behavior, you could instead access the `PlayerLayer` and seek to the beginning, something like:

```swift
videoBackground.playerLayer.player?.seek(to: kCMTimeZero)
```

**Comment by ndemie** [comment]
Thanks for the tip!

**Comment by dingwilson** [comment]
Hey @ndemie, thanks for using SwiftVideoBackground! From the conversation, it seems that you have solved your issue. Therefore, I am going to go ahead and close this. If you are still having issues, feel free to continue the discussion below (and I will reopen this issue), or create a new issue. Thanks again!
