### ISSUE TITLE
Swift 4 Compatibility

### ISSUE THREAD

**Issue by dingwilson** [dingwilson/SwiftVideoBackground#7]
'AVLayerVideoGravityResizeAspectFill' has been renamed to 'AVLayerVideoGravity.resizeAspectFill'

**Comment by AbdulazizAlmohsen** [comment]
+1

**Comment by dingwilson** [comment]
Added SwiftVideoBackground version 0.07, which fixes the above issue and provides Swift 4 compatibility.
