### ISSUE TITLE
Run the video audio in silent mode

### ISSUE THREAD

**Issue by ahmedsafadii** [dingwilson/SwiftVideoBackground#82]
How I can run the background video if the phone is silent !?

**Comment by dingwilson** [comment]
Hello @ahmedsafadii , can you provide more information?

**Comment by ahmedsafadii** [comment]
yeah I guess you need to do something like this

```
do {
    try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback)
 }
 catch {
    // report for an error
 }
```

**Comment by ahmedsafadii** [comment]
https://stackoverflow.com/questions/35289918/play-audio-when-device-in-silent-mode-ios-swift

**Comment by dingwilson** [comment]
Hey @ahmedsafadii, yes that should work! Great job finding a solution to your problem! I will go ahead and close this issue as complete. If you have any further issues, please feel free to continue the conversation, or create a new issue. Thanks!
