### ISSUE TITLE
Is it possible to use this on a UICollectionViewCell or UITableviewCell ?

### ISSUE THREAD

**Issue by yawboafo** [dingwilson/SwiftVideoBackground#83]

**Comment by dingwilson** [comment]
Hi @yawboafo , This library should work on any UIView! :) You can use the existing UIView, or add a UIView into any Cell object. Please feel free to let me know if there are any issues. Thanks! Closing.

**Comment by MohdElBasyouni** [comment]
Could you guide with an example ?
I'm trying to play video on each cell in a UITableView and it's only displaying one

**Comment by dingwilson** [comment]
Hi @Patchivic - It sounds like you are using the singleton, which only has one instance of AVPlayer. If you need to play more than one video, you will have to instantiate a `VideoBackground` object per each cell. If that is not the case, please feel free to open a new issue with some example code or how to reproduce, and I am more thank happy to help! :)
