### ISSUE TITLE
Device auto lock doesn't work when video playing (iOS 11)

### ISSUE THREAD

**Issue by blbnv** [dingwilson/SwiftVideoBackground#84]
The problem is that device does not locking automatically after 30 seconds if user does no input activity in the application with video background (in my case this is login page).

Since we use AVPlayer we can set a [property](https://developer.apple.com/documentation/avfoundation/avplayer/2990522-preventsdisplaysleepduringvideop?language=objc) `preventsDisplaySleepDuringVideoPlayback` but this one is available only on iOS 12.

Is there any ways to support that on iOS 11?

**Comment by dingwilson** [comment]
hmm interesting, I never considered auto-lock when `AVPlayer` is active. Please feel free to submit a PR with the `preventsDisplaySleepDuringVideoPlayback` implementation for > iOS 12! I will do some research when I get a chance on ways to mitigate this issue for < iOS 12.

**Comment by blbnv** [comment]
Thank you.
I will firstly research on some solution what could be appied for both 11 and 12 iOS versions.
In case of no resuluts I will submit a pull request for > iOS 12 fix.

**Comment by dingwilson** [comment]
This has been fixed as of v 3.4.0! 🎉 Closing
