### ISSUE TITLE
Playing different videos on each UITableViewCell

### ISSUE THREAD

**Issue by MohdElBasyouni** [dingwilson/SwiftVideoBackground#93]
Hi @dingwilson ,
I'm trying to create a tableView with each cell has a separate video. Assuming that the tableView cells are only 2 for the below code
Video string is placed in a static array and instances of VideoBackground

> var videoArray = ["video1", "video2", "video3", "video4", "video5"]
> let videoBackground1 = VideoBackground()
> let videoBackground2 = VideoBackground()

and inside the cellforRow indexPath method (which is weird for me, but don't know where to place, where a UIView is placed inside the cell.

> if indexPath.row == 0{
> try? videoBackground1.play(view: cell.videoView, videoName: videoArray[0], videoType: "mp4", isMuted: false)
> }else if indexPath.row == 1 {
> try? videoBackground2.play(view: cell.videoView, videoName: videoArray[1], videoType: "mp4", isMuted: false)
> }

In above case, the vice is not playing or showing, so when replacing the instance with the singleton, it's showing the last cell only due to the single AVPlayer instance.

**Comment by dingwilson** [comment]
Hey @MohdElBasyouni - try keeping an instance of `VideoBackground` inside of each TableView cell, and then calling something like:

```swift
try? cell.videoBackground.play(view: cell.contentView, videoName: videoArray[indexPath.row], videoType: "mp4", isMuted: false)
```

Assuming each cell has `videoBackground` object (instance of `VideoBackground`), and you want to play the video in the background of the TableView cell (`contentView`, or any other `UIView`)

**Comment by MohdElBasyouni** [comment]
Hey @dingwilson - it worked but,..
I'm working on a real device and the device is stopping the application with no debug error, and Xcode is again trying to reconnect to the device. Even when the application is installed and not connected to the laptop, but charging, it disconnects from the charger. 

I never have seen this behaviour, but it seems that it's too heavy on the memory or processing.

Do you have any idea of making the same instance running multiple videos?

**Comment by dingwilson** [comment]
Hey @MohdElBasyouni - I completely agree that this would be very memory intensive. Unfortunately, the core use-case/functionality for this library is to provide a single video background, for usage on things like splash screens. If you are interested in improving system resource usage, checkout https://stackoverflow.com/a/17412454 for an implementation where you can use multiple `AVPlayerItem`s within a single instance of `AVPlayer`

**Comment by MohdElBasyouni** [comment]
Hey @dingwilson - I have almost tried everything and ended up with an idea to convert the video to animated GIF and try to display the GIF in the background.
I will start checking the possibility of that and if I will face the same problem with the memory. If you recommend a certain POD, I would be grateful.
Thanks bro, you may close the issue if wanted to :)

**Comment by dingwilson** [comment]
Sounds good! Hope everything works out. :)
